#
# sample config
#   vpc/subnet with a single web server with public_ip
#
default:
  region: ${region_name}
  prefix_name: ${prefix_name}
  keypair_name: ${keypair_name}
  images:
    debian: &debian
      ami-d9937936
  vm_types:
    server_type: &server_type
      t2.micro

  cloud_init:
    cloudinit_docker: &cloudinit_docker
      #
      # install/configure docker and docker-compose package
      #
      - filename: cloud-init.yml
        content_type: text/cloud-config
        file: cloud-init/cloud-config-docker.yml
      #
      # add ssh_authorized_keys to default cloud-init account
      #
      - filename: cloud-init-ssl.yml
        content_type: text/cloud-config
        cloud-config:
          merge_how: dict(recurse_array)+list(append)
#          ssh_authorized_keys:  $__REMOVE_TO_ENABLE__{ssh_authorized_keys}

resources:
  public_ip:
    web: {}
  net:
    name: net01
    ip_range: 172.16.0.0/16
  internet_service:
    internet01:
  subnets:
    public-front-a:
      ip_range: 172.16.0.0/24
      subregion_name: a
      route:
        - destination_ip_range: 0.0.0.0/0
          gateway_id: internet01
  security_groups:
    in-ssh-from-all:
      - flow: Inbound
        rules:
          - from_port_range: "22"
            to_port_range: "22"
            ip_protocol: tcp
            ip_ranges:
              - 0.0.0.0/0
    in-web-from-all:
      - flow: Inbound
        rules:
        - from_port_range: "443"
          to_port_range: "443"
          ip_protocol: tcp
          ip_ranges:
            - 0.0.0.0/0
      - flow: Inbound
        rules:
        - from_port_range: "80"
          to_port_range: "80"
          ip_protocol: tcp
          ip_ranges:
            - 0.0.0.0/0
  instances:
    web:
      count: 1
      vm_type: *server_type
      image_id: *debian
      interfaces:
        - subnet: public-front-a
          public_ip: web    # only one public_ip associate with one instance
          security_groups:
            - in-ssh-from-all
            - in-web-from-all
      enable_user_data: true
      cloudinit_multipart: # install docker and docker-compose
        *cloudinit_docker

